services:
  game-predictor-db:
    container_name: game-predictor-db
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - game-predictor-db-volume:/var/lib/postgresql/data

volumes:
  game-predictor-db-volume:
